# Generated by Django 6.0.3 on 2026-04-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notify_new_ticket',
            field=models.BooleanField(default=True, verbose_name='Powiadamiaj o nowych zgłoszeniach'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_ticket_comment',
            field=models.BooleanField(default=True, verbose_name='Powiadamiaj o komentarzach'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_ticket_status_change',
            field=models.BooleanField(default=True, verbose_name='Powiadamiaj o zmianie statusu'),
        ),
    ]
