# Generated by Django 6.0.3 on 2026-04-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticketlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Utworzono zgłoszenie'), ('STATUS_CHANGED', 'Zmieniono status'), ('TECHNICIAN_ASSIGNED', 'Przypisano technika'), ('TECHNICIAN_REMOVED', 'Usunięto technika'), ('PRIORITY_CHANGED', 'Zmieniono priorytet'), ('CATEGORY_CHANGED', 'Zmieniono kategorię'), ('CREATOR_CHANGED', 'Zmieniono zgłaszającego'), ('ATTACHMENT_ADDED', 'Dodano załącznik'), ('TITLE_CHANGED', 'Zmieniono tytuł'), ('DESCRIPTION_CHANGED', 'Zmieniono opis')], max_length=30),
        ),
    ]
