# Generated by Django 6.0.3 on 2026-04-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticketlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_token',
            field=models.CharField(blank=True, default='', help_text='Token do akcji akceptacji/odrzucenia z e-maila', max_length=64),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Data przejścia w status Rozwiązane', null=True),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Utworzono zgłoszenie'), ('STATUS_CHANGED', 'Zmieniono status'), ('TECHNICIAN_ASSIGNED', 'Przypisano technika'), ('TECHNICIAN_REMOVED', 'Usunięto technika'), ('PRIORITY_CHANGED', 'Zmieniono priorytet'), ('CATEGORY_CHANGED', 'Zmieniono kategorię'), ('CREATOR_CHANGED', 'Zmieniono zgłaszającego'), ('ATTACHMENT_ADDED', 'Dodano załącznik'), ('TITLE_CHANGED', 'Zmieniono tytuł'), ('DESCRIPTION_CHANGED', 'Zmieniono opis'), ('ATTACHMENT_DELETED', 'Usunięto załącznik'), ('AUTO_CLOSED', 'Automatycznie zamknięto'), ('REOPENED', 'Ponownie otwarto')], max_length=30),
        ),
    ]
