# Generated by Django 6.0.3 on 2026-05-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_resolution_token_ticket_resolved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Utworzono zgłoszenie'), ('STATUS_CHANGED', 'Zmieniono status'), ('TECHNICIAN_ASSIGNED', 'Przypisano technika'), ('TECHNICIAN_REMOVED', 'Usunięto technika'), ('PRIORITY_CHANGED', 'Zmieniono priorytet'), ('CATEGORY_CHANGED', 'Zmieniono kategorię'), ('CREATOR_CHANGED', 'Zmieniono zgłaszającego'), ('ATTACHMENT_ADDED', 'Dodano załącznik'), ('TITLE_CHANGED', 'Zmieniono tytuł'), ('DESCRIPTION_CHANGED', 'Zmieniono opis'), ('ATTACHMENT_DELETED', 'Usunięto załącznik'), ('AUTO_CLOSED', 'Automatycznie zamknięto'), ('REOPENED', 'Ponownie otwarto'), ('COMMENT_ADDED', 'Dodano komentarz'), ('WORK_LOGGED', 'Zarejestrowano czas pracy')], max_length=30),
        ),
    ]
