# Generated by Django 6.0.3 on 2026-05-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticketlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('NISKI', 'Niski'), ('NORMALNY', 'Normalny'), ('WYSOKI', 'Wysoki')], db_index=True, default='NORMALNY', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NOWE', 'Nowe'), ('W_TOKU', 'W toku'), ('ROZWIAZANE', 'Rozwiązane'), ('ZAMKNIETE', 'Zamknięte')], db_index=True, default='NOWE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
