# Generated by Django 6.0.3 on 2026-05-29 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_comment_is_edited_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='Zgłoszenie nadrzędne, jeśli to jest duplikat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='related_tickets',
            field=models.ManyToManyField(blank=True, help_text='Powiązane zgłoszenia (relacja symetryczna)', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Utworzono zgłoszenie'), ('STATUS_CHANGED', 'Zmieniono status'), ('TECHNICIAN_ASSIGNED', 'Przypisano technika'), ('TECHNICIAN_REMOVED', 'Usunięto technika'), ('PRIORITY_CHANGED', 'Zmieniono priorytet'), ('CATEGORY_CHANGED', 'Zmieniono kategorię'), ('CREATOR_CHANGED', 'Zmieniono zgłaszającego'), ('ATTACHMENT_ADDED', 'Dodano załącznik'), ('TITLE_CHANGED', 'Zmieniono tytuł'), ('DESCRIPTION_CHANGED', 'Zmieniono opis'), ('ATTACHMENT_DELETED', 'Usunięto załącznik'), ('AUTO_CLOSED', 'Automatycznie zamknięto'), ('REOPENED', 'Ponownie otwarto'), ('COMMENT_ADDED', 'Dodano komentarz'), ('WORK_LOGGED', 'Zarejestrowano czas pracy'), ('MERGED', 'Oznaczono jako duplikat'), ('UNMERGED', 'Cofnięto oznaczenie duplikatu'), ('LINKED', 'Powiązano zgłoszenie'), ('UNLINKED', 'Usunięto powiązanie')], max_length=30),
        ),
    ]
